---
AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Pipeline to release Lambda layers publicly when new release is created

Metadata:
  Author: https://github.com/johnpreston

Parameters:
  RepositoryOrganization:
    Type: String
    Default: compose-x

  RepositoryProvider:
    Type: String
    AllowedValues:
      - GitHub
      - CodeCommit
    Default: GitHub
  RepositoryName:
    Type: String

  BuildLogsRetentionDays:
    Type: Number
    AllowedValues: [ 1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653 ]
    Default: 14

  ReferenceBranchName:
    Type: String
    Default: main

  LayerBuildspecFile:
    Type: String
    Default: .cicd/buildspec_layer.yml

  PublicBucketName:
    Type: String

Mappings:
  RepoUrlPrefixes:
    GitHub:
      Prefix: https://github.com/

Conditions:
  UseGitHub: !Equals [ !Ref RepositoryProvider, 'GitHub' ]
  UseCodeCommit: !Equals [ !Ref RepositoryProvider, 'CodeCommit' ]

Resources:
  BuildLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub 'codebuild/pr-builds/${RepositoryName}'
      RetentionInDays: !Ref BuildLogsRetentionDays

  PublicAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - !Sub 'codebuild.${AWS::URLSuffix}'
      Policies:
        - PolicyName: BuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: CloudWatchLogs
                Effect: Allow
                Action:
                  - logs:GetLogEvents
                Resource:
                  - !Sub '${BuildLogsGroup.Arn}'

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - !Sub 'codebuild.${AWS::URLSuffix}'
      Policies:
        - PolicyName: BuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: CloudWatchLogs
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub '${BuildLogsGroup.Arn}'
              - Sid: CodeBuildReportsAccess
                Effect: Allow
                Resource:
                  - !Sub 'arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/*'
                Action:
                  - codebuild:UpdateReportGroup
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPut*
              - Sid: CodeBuildBatch
                Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:RetryBuild
                Resource:
                  - !Sub 'arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: PublicBucketObjectsAccess
                Effect: Allow
                Action:
                  - s3:PutObject*
                  - s3:GetObject*
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${PublicBucketName}/*'
              - Sid: PublicBucketAccess
                Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${PublicBucketName}'

  LayerBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref AWS::StackName
      Visibility: PUBLIC_READ
      ResourceAccessRole: !GetAtt PublicAccessRole.Arn
      ServiceRole: !GetAtt 'CodeBuildRole.Arn'
      Description: !Sub 'Publishes new AWS Lambda layer on updates'
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref BuildLogsGroup
          Status: ENABLED
          StreamName: layer-builds
      BadgeEnabled: True
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: PUBLIC_FILES_BUCKET
            Value: !Ref PublicBucketName
            Type: PLAINTEXT
      Source:
        Type: GITHUB
        ReportBuildStatus: True
        Location: !If
          - UseGitHub
          - !Sub 'https://github.com/${RepositoryOrganization}/${RepositoryName}'
          - !Sub 'https://codecommit.${AWS::Region}.${AWS::URLSuffix}'
        InsecureSsl: False
        BuildSpec: !Ref LayerBuildspecFile
      Triggers:
        Webhook: True
        FilterGroups:
          - - Type: EVENT
              Pattern: "PULL_REQUEST_MERGED"
              ExcludeMatchedPattern: False
            - Type: HEAD_REF
              Pattern: '^refs/heads/.*$'
              ExcludeMatchedPattern: False
            - Type: BASE_REF
              Pattern: !Sub '^refs/heads/${ReferenceBranchName}$'
              ExcludeMatchedPattern: False
          - - Type: EVENT
              Pattern: "PUSH"
              ExcludeMatchedPattern: False
            - Type: HEAD_REF
              Pattern: !Sub '^refs/tags/v.*$'
              ExcludeMatchedPattern: False
