AWSTemplateFormatVersion: "2010-09-09"
Description:
  Template to deploy the Lambda layer and functions for ECS Scaling Scheduler

Transform:
  - AWS::Serverless-2016-10-31

Metadata:
  Maintainer: john@compose-x.io

Resources:

  ###############################################
  # Layer

  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      CompatibleRuntimes:
        - python3.8
      ContentUri: ${S3_LAYER_UPLOAD_PATH}
      Description: ECS Scaling Scheduler helpers
      LayerName: ecs-scaling-scheduler
      LicenseInfo: MPL-2.0
